topology: "adapt_ff_v1"

adapt_ff_v1:
  num_inputs: 1
  
adapt_ff_v2:
  num_inputs: 1

  
lif_params:
  method: "super"
  v_reset: -0.3
  v_th: 0.3

linear_params:
  init:
    - "normal"
    - 0.5
    - 0.05
  bias: False

astro_params:
  state_update_algo: ""
  effect_params: ""

  # State target
  activity_params_target:
    effect_algo: "astro_proportional_target_effect"
    alpha: 1.0
    target: 0.0

  # Exp average state vs presynaptic activity
  activity_params_pre:
    effect_algo: "astro_proportional_effect"
    
data:
  gen: "poisson_ramp"
  width: 1
  stops: null
  steps: 1000

learning:
  rule: "stdp"
  decay_fn: "recent"
  optimize: False

sim:
  dt: 0.001
  iters: 1000

meta:
  experiments:
    - "astro_adapt_post_target"
    # - "astro_adapt_post_target_multi"
    # - "astro_adapt_pre"
    # - "astro_adapt_pre_multi"

  astro_adapt_post_target: &at1
    # Overlay on main config, with ranges for some parameters
    variation_strategy: 'foreach'
    graphs: ['range_v_state_alpha', 'volume_v_state_alpha']
    overlay:
      topology: "adapt_ff_v1"
      adapt_ff_v1:
        num_inputs: 1
      data:
        stops: [0.2, 5, 0.2]
      astro_params:
        state_update_algo: "astro_state_prop_inc_exp_decay"
        tau: 80
        alpha: "linspace(0.1, 1.5, 10)"
        
        effect_params: "activity_params_target"
        activity_params_target:
          alpha: 1.0
          target: 0.0


  astro_adapt_post_target_multi:
    # __inherit__: *at1
    overlay:
      adapt_ff_v1:
        num_inputs: 3
      data:
        width: 3
        stops:
          - [0.2]
          - [0.5]
          - [0.01]
      linear_params:
        init:
          - "normal"
          - 0.05
          - 0.01


  astro_adapt_pre: &at2
    # Overlay on main config, with ranges for some parameters
    variation_strategy: 'foreach'
    graphs: ['range_v_state_alpha', 'volume_v_state_alpha']
    overlay:
      topology: "adapt_ff_v2"
      adapt_ff_v2:
        astro_after_linear: False
      data:
        stops: [0.2, 1, 0.2, 1, 0.2]
      astro_params:
        state_update_algo: "astro_state_exp_avg"
        alpha1: 0.005
        alpha2: 0.02
        
        effect_params: "activity_params_pre"
        activity_params_pre:
          alpha: -0.7


  astro_adapt_pre_multi:
    __inherit__: *at2
    overlay:
      adapt_ff_v2:
        num_inputs: 3
      data:
        width: 3
        stops:
          - [0.2]
          - [0.5]
          - [0.01]
      linear_params:
        init:
          - "normal"
          - 0.05
          - 0.01
      astro_params:
        activity_params_pre:
          alpha: -0.2
