topology: "adapt_ff_v1"

adapt_ff_v1:
  input:
    num: 1
    type: "input"

  lif:
    num: 1
    type: "lif"

lif_params:
  method: "super"
  v_reset: -0.3
  v_th: 0.3

linear_params:
  init:
    - "normal"
    - 0.5
    - 0.05
  bias: False

astro_params:
  state_update_algo: "astro_state_prop_inc_exp_decay"
  tau: 100.0
  alpha: 1.0

  activity_params: ""
  
  # Constant current
  activity_params_const:
    affect_algo: "astro_const_effect"
    thr: 0.3
    const_effect: 0.5

  # State target
  activity_params_target:
    affect_algo: "astro_proportional_effect"
    alpha: 1.0
    target: 3

  # Inc/Dec band
  activity_params_inc_dec:
    affect_algo: "astro_inc_dec_effect"
    inc_low_thr: 2
    inc_step: 0.1
    max: 0.5
    dec_high_thr: 8
    dec_step: 0.3
    min: -0.5

data:
  gen: "poisson_ramp"
  width: 1
  stops: [0.5, 2, 0.5]
  steps: 1000

learning:
  rule: "stdp"
  decay_fn: "recent"
  optimize: True

sim:
  dt: 0.001
  iters: 1000
  name_fn: "_name_from_cfg"

meta:
  experiments: ["exp_target"]
  
  exp_target:
    # Overlay on main config, with ranges for some parameters
    name_fn: '_exp_name_from_cfg'
    variation_strategy: 'foreach'
    overlay:
      astro_params:
        # Vary tau and alpha with a linspace according to specified params
        tau: "linspace(0, 100, 4)"
        alpha: "linspace(0, 1.0, 4)"
        activity_params: "activity_params_target"
        activity_params_target:
          target: 3
