topology: "adapt_ff_v1"

adapt_ff_v1:
  input:
    num: 1
    type: "input"
    next: ["linear"]
    last: null

  linear:
    num: 1
    type: "linear"
    next: ["lif"]
    last: ["input"]

  lif:
    num: 1
    type: "lif"
    last: ["linear", "astro"]
    next: null

  astro:
    num: 1
    type: "astro"
    last: ["lif"]
    next: ["linear"]

lif_params:
  method: "super"
  v_reset: -0.3
  v_th: 0.3

linear_params:
  init:
    - "normal"
    - 0.5
    - 0.05
  bias: False

astro_params:
  alpha: null
  tau: null
  
  state_update_algo: ""
  effect_params: ""

  # State target
  activity_params_target:
    effect_algo: "astro_proportional_target_effect"
    alpha: 1.0
    target: 3

  # Exp average state vs presynaptic activity
  activity_params_pre:
    effect_algo: "astro_proportional_effect"
    alpha: 1.0
    
data:
  gen: "poisson_ramp"
  width: 1
  stops: null
  steps: 1000

learning:
  rule: "stdp"
  decay_fn: "recent"
  optimize: False

sim:
  dt: 0.001
  iters: 1000

meta:
  experiments: ["astro_adapt_post_target"]

  astro_adapt_post_target:
    # Overlay on main config, with ranges for some parameters
    variation_strategy: 'foreach'
    overlay:
      data:
        stops: [0.2]
      astro_params:
        # Vary tau and alpha with a linspace according to specified params
        state_update_algo: "astro_state_prop_inc_exp_decay"
        tau: 80
        alpha: 0.01
        
        effect_params: "activity_params_target"


  astro_adapt_pre:
    # Overlay on main config, with ranges for some parameters
    variation_strategy: 'foreach'
    overlay:
      data:
        stops: [0.2]
      astro_params:
        state_update_algo: "astro_state_exp_avg"
        tau: 80
        alpha: 0.01
        effect_params: "activity_params_pre"
