topology:
  input:
    num: 100
    type: "input"
    
  lif0:
    num: 1
    type: "lif"

lif_params:
  method: "super"
  v_reset: -0.3
  v_th: 0.3

linear_params:
  init:
    - "normal"
    - 0.5
    - 0.05
  bias: False

learning:
  rule: "rstdp"
  epochs: 10
  iters_per_epoch: 100
  correlated_inputs: False
  decay_fn: "recent"
  optimize: True
  reward_fn: "_onehot_reward"

data:
  gen: "onehot"
  width: 100
  target_ratio: 0.5

sim:
  dt: 0.001
